apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  component_id: ${{values.component_id | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}